# Generated by Django 5.0.6 on 2024-08-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_signup',
            new_name='admin_sign',
        ),
    ]
