# Generated by Django 5.0.6 on 2024-08-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_rename_admin_signup_admin_sign'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_sign',
            new_name='admin_register',
        ),
    ]
