# Generated by Django 5.0.6 on 2024-08-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0005_alter_admin_register_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_register',
        ),
    ]
