# Generated by Django 5.0.6 on 2024-08-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0008_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(default='', upload_to='./braand')),
            ],
        ),
    ]
