# Generated by Django 5.0.6 on 2024-08-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0009_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(default='', upload_to='./category')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(default='', upload_to='./brand'),
        ),
    ]
