# Generated by Django 5.0.6 on 2024-08-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0012_rename_name_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='category_name',
            field=models.CharField(max_length=10),
        ),
    ]
