# Generated by Django 5.0.6 on 2024-08-30 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0013_alter_sub_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='category_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.category'),
        ),
    ]
