# Generated by Django 5.0.6 on 2024-08-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0015_delete_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('subcategory_name', models.CharField(max_length=50)),
                ('image', models.FileField(default='', upload_to='./subcategory')),
            ],
        ),
    ]
