# Generated by Django 5.0.6 on 2024-08-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0016_sub_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
