# Generated by Django 5.0.6 on 2024-08-31 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0021_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sign_up',
        ),
    ]
