# Generated by Django 5.0.6 on 2024-08-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0022_delete_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.FileField(default='', upload_to='./sign_up_profile/')),
            ],
        ),
        migrations.DeleteModel(
            name='slide',
        ),
    ]
