# Generated by Django 5.0.6 on 2024-08-31 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0023_sign_up_delete_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=500)),
                ('image', models.FileField(default='', upload_to='./slide')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_name',
        ),
        migrations.DeleteModel(
            name='brand',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='sub_category',
        ),
    ]
