# Generated by Django 5.0.6 on 2024-08-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0025_brand_category_sub_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
