# Generated by Django 5.0.6 on 2024-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('image', models.FileField(default='', upload_to='./user_profile')),
            ],
        ),
    ]
