# Generated by Django 5.0.6 on 2024-09-16 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0026_remove_category_image'),
        ('front_end', '0003_signup_status_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='WISHLIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('prize', models.BigIntegerField()),
                ('sub_total', models.BigIntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_side.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front_end.signup')),
            ],
        ),
    ]
